[tool.pylint.messages_control]
disable = "C0330, C0326, W1203"

[tool.pylint.format]
max-line-length = "88"
good-names="i,j,k,e"

[tool.pylint.master]
init-hook = 'import sys; import os; sys.path.append(os.getcwd() + "/src");'

[tool.isort]
profile = "black"

[tool.vulture]
min_confidence = 80
